### PR TITLE
Adds empty Apollo gradle task and compiler

### PR DESCRIPTION
**Pull request by felipecsl**
More boilerplate code 😄 
Having a separate compiler project allows us to potentially share the implementation with other project types (not just Android, but also pure Java, server apps, etc).

### CODE REVIEW

**Comment by felipecsl** [comment]
ping!

**Comment by martijnwalraven** [comment]
@felipecsl: This looks good to me, but I don't really know anything about Gradle builds, so I don't feel I have much to add here. Maybe @jpshelley can chime in?

**Comment by jpshelley** [comment]
To be honest don't know that much about it either at this point. I'd say merge and if we need to edit it later we can do so.

**Comment by rafaelwkerr** [comment]
Hi folks, I'm interested in working on this OSS, which is the prerequisite?

**Pull request merged**
