### PR TITLE
change annotations to provided scope

### LINKED ISSUE #116: Change annotation dependency scope to provided
Currently we are packaging in the annotation dependencies which conflict with Espresso. This is an issue tracking the change from compile to provided

### PR DESCRIPTION
**Pull request by digitalbuddha**
Let me know if something looks hairy :-)

closes #116

### CODE REVIEW

**Comment by digitalbuddha** [comment]
not exactly right, I'll take a look later again

**Comment by felipecsl** [comment]
hmmm not sure why this didn't work. Maybe I don't understand it as well as I thought 😛

**Comment by digitalbuddha** [comment]
Lol same

**Comment by digitalbuddha** [comment]
closing for now, will revisit

**Pull request closed without merging**
